#ifndef LINUX_IF_EQL_H
#define LINUX_IF_EQL_H

#define EQL_EMANCIPATE (SIOCDEVPRIVATE+1)
#define EQL_ENSLAVE (SIOCDEVPRIVATE)
#define EQL_GETMASTRCFG (SIOCDEVPRIVATE+4)
#define EQL_GETSLAVECFG (SIOCDEVPRIVATE+2)
#define EQL_SETMASTRCFG (SIOCDEVPRIVATE+5)
#define EQL_SETSLAVECFG (SIOCDEVPRIVATE+3)

#endif
